### PR TITLE
Update Dabase, add owners, species tables

### PR DESCRIPTION
**Pull request by Lookingfor00**
In this pull request, I have been able to:
- Add owners table
- Add species table
- Add data in data.sql
- Add queries answer into queries.sql

pr1
pr2

### CODE REVIEW

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Allassane, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦   🏃 

## Highlights 👍  
- Joining, updating & querying multiple tables properly done!

## Required Changes ♻️
- [x] MIT license link in your ReadMe is broken, kindly endeavor to fix it.

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lookingfor00** [comment]
Hi @rloterh, thank you for the review. I will definitely solve that! 👍 
I admire your attention to detail, but I'm not sure if this review is actually a requirement, I think it looks more like an **optional change** than a project requirement.

**Comment by rloterh** [comment]
> Hi @rloterh, thank you for the review. I will definitely solve that! 👍 I admire your attention to detail, but I'm not sure if this review is actually a requirement, I think it looks more like an **optional change** than a project requirement.

Hi @Trast00 

You are right, that wasn't a part of the project requirement!
However recently, as a general requirement this and all other projects needs ensure that the license is properly added before that particular project can be approved!

Cheers! 😃

**Review by m05e5 — APPROVED** [review]
**Hi @Trast00 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
CleverScornfulBuffalo-size_restricted

## Highlights

✔️ Good PR description

## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

**Pull request merged**
